apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-server-deployment2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: model-server
  template:
    metadata:
      labels:
        app: model-server
    spec:
      containers:
      - name: model-server-container2
        image: model-server:custom
        env:
        - name: MODEL_PATH
          valueFrom:
            configMapKeyRef:
              name: model-path-config
              key: model-path
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
        volumeMounts:
        - name: model-volume
          mountPath: /mount
      volumes:
      - name: model-volume
        hostPath:
          path: /tmp
          type: Directory
